const CartActionTypes = {
  TOGGLE_CART_HIDDENT: "TOGGLE_CART_HIDDENT",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  INCREASE: "INCREASE",
  DECREASE: "DECREASE",
};

export default CartActionTypes;
